spring:
  application:
    name: E-commerce
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}?autoreconnect=true
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:ecommerce}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  main:
    lazy-initialization : true

  flyway:
    # locations: filesystem:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    schemas: ${DB_SCHEMA:ecommerce}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

